server:
  port: "8080"
  readTimeout: "15s"
  writeTimeout: "15s"
  idleTimeout: "60s"

database:
  url: postgres://postgres:postgres@localhost:5432/go_rest_api?sslmode=disable
  maxConnections: 10
  minConnections: 2
  maxConnLifetime: "1h"
  maxConnIdleTime: "30m"

jwt:
  secret: your-secret-key-change-in-production
  expirationTtl: "24h"
